//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetb.Models.data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int idCustomer { get; set; }

        [Required(ErrorMessage = "Requis")]
        [Display(Name = "Nom")]
        public string lastname { get; set; }

        [Required(ErrorMessage = "Requis")]
        [Display(Name = "Prénom")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "Requis")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string mail { get; set; }

        [Required(ErrorMessage = "Requis")]
        [MinLength(10, ErrorMessage = "Un numéro possède 10 chiffres")]
        [Phone]
        [Display(Name = "N° téléphone")]
        public string phoneNumber { get; set; }

        [Required(ErrorMessage = "Requis")]
        [Display(Name = "Budget")]
        public int budget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}
